### ISSUE TITLE
the networks is inconsistent with hujie-frank/SENet

### ISSUE THREAD

**Issue by lc82111** [titu1994/keras-squeeze-excite-network#1]
Thank you for your keras implementation which is very helpfull.
But, I found several inconsistencies.
For example, the first conv layer should do stride (2, 2) conv.
For example, the residual block should have THREE rather than TWO conv layer.

**Comment by titu1994** [comment]
Fixed. Its not an exact match to the original resnet paper, because it is based on the Keras port of the ResNet50 model.
