### ISSUE TITLE
Add a License?

### ISSUE THREAD

**Issue by BastiQ** [titu1994/keras-squeeze-excite-network#13]
"When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you. ..."

From: https://choosealicense.com/no-permission/

**Comment by titu1994** [comment]
Added in 749fea1763868780b7515e58f5e0033e9a0e24f3
