### ISSUE TITLE
A trivial typo of spatial SE block

### ISSUE THREAD

**Issue by wzhings** [titu1994/keras-squeeze-excite-network#15]
Hello, I just found a tiny typo in the spatial_squeeze_excite_block function of se.py.
It should be:
`se = Conv2D(1, (1, 1), activation='sigmoid', use_bias=False,
kernel_initializer='he_normal')(input)`

**_(input)_** should be append in the end of the above code. 
I know it is trivial. hope not to confuse anyone who want to call it. Thanks.

**Comment by titu1994** [comment]
Patched via dc1bc030c9e8790c4a1dc4ba77776119652bd6d0
