### ISSUE TITLE
No Bias in Dense Layers

### ISSUE THREAD

**Issue by pGit1** [titu1994/keras-squeeze-excite-network#5]
Could not find this in paper. Is there a reason we don't use a bias in the Dense layers within the SE block?

**Comment by titu1994** [comment]
Because the original code doesn't mention biases.

Also, Since the layers themselves have no bias, even the squeeze excite block has no biases.

**Comment by rederyang** [comment]
> Could not find this in paper. Is there a reason we don't use a bias in the Dense layers within the SE block?

You could find it in section 6 in the paper.
