### ISSUE TITLE
Is weights='imagenet' option currently available?

### ISSUE THREAD

**Issue by desertnaut** [titu1994/keras-squeeze-excite-network#6]
I am a little confused regarding the `weights` argument in `SEResNet()`.

According to the source code of `se_resnet.py`, `weights='imagenet'`  is an option; but I cannot see any weights actually loaded in the code (there is a comment, `#load weights` in [line 143](https://github.com/titu1994/keras-squeeze-excite-network/blob/master/se_resnet.py#L143), but there is no code after it.

Should I guess that the subject option is there only for future proofing, i.e. for when pre-trained weights will be available for loading, and is not currently functional, or I am missing something and I can indeed use a pretrained `SEResNet()` with ImageNet weights?

Many thanks in advance

**Comment by titu1994** [comment]
Yes it's for future proofing. Currently the weights have not been ported yet, since I am on Windows and cannot use Torch or PyTorch.
